--- #YAML:1.0
name:               Pod-Parser
version:            1.36
abstract:           Modules for parsing/translating POD format documents
author:
    - Brad Appleton <bradapp@enteract.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0.6
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
